-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "total" DROP DEFAULT,
ALTER COLUMN "total" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "Cabin" ALTER COLUMN "price" SET DATA TYPE DECIMAL(10,2);
